name: Manual Trigger Random String PR

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  create-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate random string and create file
        run: |
          UUID=$(uuidgen)
          echo $UUID > UUID
          echo "Generated UUID: $UUID"
          echo "UUID=$UUID" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch and commit changes
        run: |
          BRANCH_NAME="random-string-$UUID"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          git checkout -b $BRANCH_NAME
          git add UUID
          git commit -m "New UUID: $UUID"
          git push origin $BRANCH_NAME

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create --title "Add random string file" \
                       --body "This PR adds a file with a random string." \
                       --head "$BRANCH_NAME" \
                       --base "main"
